### ISSUE TITLE
Feed not loading 

### ISSUE THREAD

**Issue by android-smiley** [j-fbriere/squawker#2]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/j-fbriere/squawker/releases).
- [X] I made sure that there are *no existing issues* - [open](https://github.com/j-fbriere/squawker/issues) or [closed](https://github.com/j-fbriere/squawker/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug, that only occurs in Squawker

### Affected version

v3.0.0+300003129

### Steps to reproduce the bug

1. Open App
2. Refresh the feed page

### Expected behavior

Tweets and profiles should be displayed. 

### Actual behavior

An error message is appearing, stating that the search results/ tweets can't be loaded. In the next line it's saying "Instance of 'qB'". 

### Affected Android/Custom ROM version

GrapheneOS 2023062800 (latest) / Android 13(TQ3A.230605.012)

### Affected device model

Pixel 7 Pro 

### Additional information

Issue appears app-wide, there's no difference with restoring accounts from Quacker/Fritter backup or trying to access accounts or trends (trend page itself is loading) from a fresh installation of the app.

This issue appeared as well on the last available Quacker version.

**Comment by j-fbriere** [comment]
Yes it is due to changes made by Twitter.
Elon Musk has written that those changes are temporary.

See: [nitter #919 comment #1x](https://github.com/zedeus/nitter/issues/919#issuecomment-1615136091)
Also: [nitter #919 comment #2](https://github.com/zedeus/nitter/issues/919#issuecomment-1616016482)

I guess we'll have to wait and see.

**Comment by AndiDink00x** [comment]
We got really F'ed by mister "free speech" lets hope not permanently

**Comment by rsssxd** [comment]
@j-fbriere 

Twitter is better. Will the feed flow return?

**Comment by j-fbriere** [comment]
@rsssxd What do you mean "Twitter is better"?

The problem is that right now the SearchTimeline graphql call from the Twitter API (the one that is used for the feed and groups) returns nothing for a guest account (without login).
But since things are slowly coming back to "normal" with Twitter, I would wait a couple of days.
