### ISSUE TITLE
can't download "Squawker" from the IzzyOnDroid repo?

### ISSUE THREAD

**Issue by useless642** [j-fbriere/squawker#55]
I added the IzzyOnDroid repo to [Foxy Droid](https://github.com/kitsunyan/foxy-droid), but when I search for "Squawker", there's no visible button to install it:

| ![Screenshot_2023-08-27_19-27-41.png](https://github.com/j-fbriere/squawker/assets/85243826/db5daf6b-b315-4080-84d8-121f93adaeb7) | ![Screenshot_2023-08-27_19-27-50.png](https://github.com/j-fbriere/squawker/assets/85243826/fe8dd9ca-95b0-4c3a-8d6c-2a027cd63be0) |
| --- | --- |

the app is grayed out, and there's no way to install it. (?)

**Comment by nameless326** [comment]
if I enable "Incompatible versions", they show up but they show this error:

| ![Screenshot_2023-08-27_22-10-14.png](https://github.com/j-fbriere/squawker/assets/85243826/70b29d40-5654-45d3-89fc-2b31617aec48) | ![Screenshot_2023-08-27_22-10-44.png](https://github.com/j-fbriere/squawker/assets/85243826/ecea40db-d97d-48c4-bb85-73e3e9831659) | ![Screenshot_2023-08-27_22-10-55.png](https://github.com/j-fbriere/squawker/assets/85243826/527800e1-78b2-4d72-8ca4-4a694eccab82) |
| --- | --- |

... which doesn't make any sense, because I can install Squawker from GitHub with no problems whatsoever.

**Comment by j-fbriere** [comment]
I just installed Foxy Droid.
Then I added the IzzyOnDroid repository (https://apt.izzysoft.de/fdroid/repo).
Then I can see that Squawker is available to install.
I didn't activate the setting to show incompatible versions.
|![Screenshot_20230827-223000_Foxy Droid](https://github.com/j-fbriere/squawker/assets/49044668/4992b769-c438-4e42-81d4-a1c526fca647)|![Screenshot_20230827-223018_Foxy Droid](https://github.com/j-fbriere/squawker/assets/49044668/5904fe64-e1f2-40f3-b007-0f0f6490b889)|![Screenshot_20230827-223146_Foxy Droid](https://github.com/j-fbriere/squawker/assets/49044668/e223cf18-01fd-4fce-a85e-b0274deadbc8)|
| --- | --- | --- |

Which version of Android is your device?

**Comment by nameless326** [comment]
> Which version of Android is your device?

Android 9, with armeaby-v7a CPU structure.

I just checked, and it seems that [IzzyOnDroid](https://apt.izzysoft.de/fdroid/repo/org.ca.squawker_300003196.apk] is using this [version](https://github.com/j-fbriere/squawker/releases/download/v3.4.2/squawker-v3.4.2_arm64-v8a.apk) of Squawker, which is incompatible with my device.

(they both share the same HASH: 735a66efaafcee68efadcf82599d119b71735d86)

it should be picking up this other [version](https://github.com/j-fbriere/squawker/releases/download/v3.4.2/squawker-v3.4.2.apk), instead... which is the generic one.

**Comment by nameless326** [comment]
is there a way to let him know that?

**Comment by j-fbriere** [comment]
Unfortunately IzzyOnDroid would not accept the big apk (which contains all the 3 different architectures) because of its size.
The maximum size accepted is 30 Mb and the apk is 33 Mb...
So I had to choose the most popular architecture, which is the arm64-v8a one.

**Comment by nameless326** [comment]
that would be awesome, thanks!

**Comment by nameless326** [comment]
the only other option would be uploading Squawker to the official F-Droid repo.

they build their own apps there.

what do you think?

**Comment by j-fbriere** [comment]
I'll have a look.

**Comment by j-fbriere** [comment]
I made a merge request for Squawker to the F-Droid repository.
We'll have to wait and see if it's accepted.

**Comment by j-fbriere** [comment]
Follow-up: After many attempts my build script has been merged the the F-Droid repository. 
Squawker will appear on their site after being built and signed in a couple of days.
Coming soon...

**Comment by nameless326** [comment]
thank you so much!

**Comment by j-fbriere** [comment]
The application is now on [F-Droid](https://f-droid.org/packages/org.ca.squawker).
You can now choose the appropriate apk to install for your device (in your case the armeabi-v7a one, which is the second apk in the page).

**Comment by useless642** [comment]
you're awesome, thank you so much!

**Comment by j-fbriere** [comment]
Closing this issue since Squawker is now on F-Droid.

After talking with the IzzyOnDroid repository owner, I understand that this repository is aim at the github built applications, not the F-Droid ones.
Now that Squawker is on F-Droid, he told me that it would be confusing to have Squawker also on IzzyOnDroid because both repositories point to different builds of Squawker, with different signatures, and one type cannot update from the other (because of the difference of signatures).
So I asked to remove Squawker from the IzzyOnDroid repository.
