### ISSUE TITLE
Dont show update notification if installed from f-droid

### ISSUE THREAD

**Issue by Aegeontis** [j-fbriere/squawker#60]
### Describe the problem

I get a notification about a newer version being available on github when I open the app. I installed the app from the izzyondroid repo (which means I dont wanna manually update it)

### Describe the solution

Squawker should determine whether it has an F-droid/IzzyOnDroid signature and only show a notification if it doesnt.

**Comment by j-fbriere** [comment]
The application will soon be on F-Droid.
Then I will make a request on IzzyOnDroid to use the F-Droid repository instead of github.
Then when the application comes from IzzyOnDroid or F-Droid it will not show any notification for update on opening.
Coming soon.

**Comment by j-fbriere** [comment]
After talking with the IzzyOnDroid repository owner, I understand that this repository is aim at the github built applications, not the F-Droid ones.
Now that Squawker is on F-Droid, he told me that it would be confusing to have Squawker also on IzzyOnDroid because both repositories point to different builds of Squawker, with different signatures, and one type cannot update from the other (because of the difference of signatures).
So I asked to remove Squawker from the IzzyOnDroid repository.

Closing this issue.
